version: '3.8'

services:
  mongodb:
    image: percona/percona-server-mongodb:7.0.5-3-multi
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/db:/var/lib/mongo
      - ./mongo/log:/var/log/mongo
      - ./mongo/mongod.key:/etc/mongod.key
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/root-username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/root-password
    secrets:
      - root-username
      - root-password
    command: [
      "--keyFile=/etc/mongod.key",
      "--logpath=/var/log/mongo/mongod.log",
      "--dbpath=/var/lib/mongo",
      "--bind_ip_all",
      "--port=27017"
    ]
  gateway-server:
    depends_on:
      - mongodb
      - auth-server
      - event-server
    build:
        context: ../
        dockerfile: ./docker/gateway.dockerfile
    container_name: gateway-server
    ports:
      - "30000:30000"
  event-server:
    depends_on:
      - mongodb
    build:
      context: ../
      dockerfile: ./docker/event.dockerfile
    container_name: event-server
    ports:
      - "30001:30001"
  auth-server:
    depends_on:
      - mongodb
    build:
      context: ../
      dockerfile: ./docker/auth.dockerfile
    container_name: auth-server
    ports:
      - "30002:30002"
      - "50051:50051"
volumes:
  mongo:

secrets:
  root-username:
    file: ./mongo/root-username
  root-password:
    file: ./mongo/root-password